- name: Configure Python Environment
  hosts: localhost
  vars:
    uv_version: "0.11.0"
    uv_checksum: "cc0fbb42b3642125f600a55b0b095bea65cddaadb94c6ea2b6ba5d79c5825089"
    python_versions:
      - "3.10"
      - "3.11"
      - "3.12"
      - "3.13"
  become: false
  environment:
    TMPDIR: "{{ alt_tmpdir | default('/tmp') }}"
  tasks:
    - name: Create temporary directory
      ansible.builtin.tempfile:
        state: directory
        suffix: ansible
      register: tmpdir
      check_mode: false

    - name: Download uv
      ansible.builtin.get_url:
        url: "https://releases.astral.sh/github/uv/releases/download/{{ uv_version }}/uv-x86_64-unknown-linux-gnu.tar.gz"
        dest: "{{ tmpdir.path }}"
        mode: "0700"
        checksum: "sha256:{{ uv_checksum }}"

    - name: Extract uv
      ansible.builtin.unarchive:
        src: "{{ tmpdir.path }}/uv-x86_64-unknown-linux-gnu.tar.gz"
        dest: "{{ ansible_env.HOME }}/.local"
      args:
        creates: "{{ ansible_env.HOME }}/.local/uv-x86_64-unknown-linux-gnu"

    - name: Add uv to path
      ansible.builtin.lineinfile:
        path: "{{ ansible_env.HOME }}/.bashrc_local"
        line: "export PATH={{ ansible_env.HOME }}/.local/uv-x86_64-unknown-linux-gnu:$PATH"
        mode: "0644"
        create: true

    - name: Install python versions
      ansible.builtin.shell: |
        export PATH="{{ ansible_env.HOME }}/.local/uv-x86_64-unknown-linux-gnu:$PATH"
        uv python install {{ item }}
      changed_when: false
      args:
        executable: /bin/bash
      with_items: "{{ python_versions }}"
